Repository siteline/SwiftUI-Introspect, pull requests merged in 2020-02, with the labels that each got.

#10 Fix Circle CI badge URL
  README.md
Labels: size/XS

#11 Feature/generic ui view introspection
  Introspect/Introspect.swift
Labels: size/M

#12 macOS and tvOS support
  .circleci/config.yml
  CHANGELOG.md
  Introspect.podspec
  Introspect.xcodeproj/project.pbxproj
  Introspect.xcodeproj/xcshareddata/xcschemes/Introspect iOS.xcscheme
  Introspect.xcodeproj/xcshareddata/xcschemes/Introspect macOS.xcscheme
  Introspect.xcodeproj/xcshareddata/xcschemes/Introspect tvOS.xcscheme
  Introspect.xcodeproj/xcuserdata/ldiqual.xcuserdatad/xcschemes/xcschememanagement.plist
  Introspect/AppKitIntrospectionView.swift
  Introspect/Info.plist
  Introspect/Introspect.swift
  Introspect/UIKitIntrospectionView.swift
  Introspect/UIKitIntrospectionViewController.swift
  Introspect/ViewExtensions.swift
  IntrospectExamples/Assets.xcassets/AppIcon.appiconset/Contents.json
  IntrospectExamples/Assets.xcassets/Contents.json
  IntrospectExamples/Base.lproj/LaunchScreen.storyboard
  IntrospectExamples/Info.plist
  IntrospectExamples/Preview Content/Preview Assets.xcassets/Contents.json
  IntrospectTests/AppKitTests.swift
  IntrospectTests/Info.plist
  IntrospectTests/TestUtils.swift
  IntrospectTests/UIKitTests.swift
  Package.swift
  README.md
  fastlane/Fastfile
Labels: size/XXL
