Repository siteline/SwiftUI-Introspect, pull requests merged in 2021-03, with the labels that each got.

#76 Use Xcode 12.4.0 on CircleCI
  .circleci/config.yml
  CHANGELOG.md
Labels: size/XS

#52 Added introspect for SwiftUI's TextEditor
  CHANGELOG.md
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
Labels: size/M

#78 Add GitHub action
  .github/workflows/build-and-test.yml
  CHANGELOG.md
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
Labels: size/L

#18 Adds an introspect method for UITableViewCell
  CHANGELOG.md
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
  README.md
Labels: size/M

#69 Fix an issue where nested ScrollViews would not be detected properly
  CHANGELOG.md
  Introspect/Introspect.swift
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
Labels: size/L

#79 Update README
  README.md
Labels: size/S

#82 Improve GitHub CI runtime
  .github/workflows/build-and-test.yml
  Gemfile
  Gemfile.lock
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: size/M

#84 Add introspection for `NSTabView`
  CHANGELOG.md
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
Labels: enhancement, size/M

#83 Fix UITextField with cornerRadius
  CHANGELOG.md
  Introspect/Introspect.swift
  Introspect/ViewExtensions.swift
  IntrospectTests/UIKitTests.swift
Labels: size/L

#85 Add NSButton Introspection
  CHANGELOG.md
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
Labels: enhancement, size/S

#87 Add .introspectColorWell()
  CHANGELOG.md
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
Labels: enhancement, size/M

#89 Add .introspectSplitViewController() on iOS
  .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  CHANGELOG.md
  Introspect/Introspect.swift
  Introspect/ViewExtensions.swift
  IntrospectTests/UIKitTests.swift
Labels: size/M

#91 Update README.md
  README.md
Labels: size/S

#92 Test and document using introspectButton for Toggle on macOS
  IntrospectTests/AppKitTests.swift
  README.md
Labels: size/S

#94 Add findChildUsingFrame to README
  README.md
Labels: size/XS
