Repository siteline/SwiftUI-Introspect, pull requests merged in 2023-02, with the labels that each got.

#168 Static/dynamic library products
  Package.swift
Labels: size/XS

#165 Fix view controller introspection
  Introspect/UIKitIntrospectionView.swift
  Introspect/UIKitIntrospectionViewController.swift
Labels: size/M

#169 Add support for UICollectionView introspection
  Introspect/ViewExtensions.swift
  IntrospectTests/UIKitTests.swift
Labels: size/XS

#152 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#125 Add `introspectMapView`
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
  IntrospectTests/UIKitTests.swift
Labels: size/S

#129 Add `.introspectSearchController`
  Examples/Showcase/Showcase.xcodeproj/project.pbxproj
  Examples/Showcase/Showcase/ContentView.swift
  Examples/Showcase/Showcase/Helpers.swift
  Introspect/ViewExtensions.swift
  IntrospectTests/UIKitTests.swift
Labels: size/M

#100 Add support for NSplitView
  Introspect/ViewExtensions.swift
  IntrospectTests/AppKitTests.swift
  README.md
Labels: size/M
